name: LGTM Check

on:
  issue_comment:
    types: [created]

jobs:
  check-lgtm:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'LGTM')
    runs-on: ubuntu-latest
    steps:
      - name: Approve the PR with LGTM comment
        run: echo "LGTM comment detected! Fake workflow passed."
